### ISSUE TITLE
Image organization('image.name') in helm value must be spaceone 

### ISSUE THREAD

**Issue by GeunjeLEE** [cloudforet-io/dashboard#8]
helm value in `deploy.helm` is default value to support Open Source Users.

But, Currently the default value has wrong information in image.name section.
correct image organization('image.name') is `spaceone`.

```diff
image:
+   name: spaceone/dashboard # Registry for prd version
-   name: pyengine/dashboard # Registry for dev version
    version: latest
```

**Comment by stat-kwon** [comment]
thanks you, @GeunjeLEE 
I will take action as soon as possible.
